# Generated by Django 2.2.14 on 2020-12-01 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=200)),
                ('aula', models.CharField(max_length=100)),
                ('horas', models.IntegerField(null=True)),
            ],
        ),
    ]
