# Generated by Django 2.2.14 on 2020-12-01 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('enseña', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('clase_impartida', models.ManyToManyField(related_name='clase_impartida', to='clases.Clase')),
            ],
        ),
    ]
